### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [djm858/edith-wharton_the-age-of-innocence#1]
- Illegal `<style>` tag in chapter-17.xhtml

- You can remove the .sign class and instead target the sign with `#chapter-17 blockquote`

- In that blockquote, lines after `<br/>` must be at the same indentation level as the parent `<p>`

- chapter 6: Ulysses and Lotus Eaters should be quoted, as they are short poems (Idylls of the King is a book-length poem and can keep italics.)

- chapter 10: `<span xml:lang="fr"><i epub:type="se:name.publication.book">Contes Drôlatiques</i></span>` Remove the span and put the xml:lang attribute on `<i>`

- I see there's a lot of English words marked with `<span xml:lang>`. Since these words are in M-W they are now "English", so they don't need spans. That might suggest to a screen reader that they're pronounced differently, but an English screen reader will know how to pronounce them because they're in the dictionary. Just remove all of those spans please.

- I also see some spans that should be `<i>`, like `<span xml:lang="la">Sancta simplicitas!</span>`

- `se typogrify` makes a lot of changes, please run it and review them

- `se modernize-spelling` makes changes, please review them

- colophon: Remove comma after `<b class="name">Judith Boss</b>,`

**Comment by djm858** [comment]
Done.

Were there other spans besides Sancta simplicitas that needed italicized? I originally didn't because it's in M-W, but I'm not sure when something like that should be italicized anyway.

I kinda guessed on the blockquote so hopefully that's what you were asking for.

**Comment by acabal** [comment]
Can you amend your modernize spelling commit to preface it with "[Editorial]" please? That way people can more easily find these commits to undo them if they choose.

**Comment by acabal** [comment]
Also, please remove the `<style>` tag from chapter 17. `local.css` is where all styling goes, and you can target that blockquote in `local.css` by using the `#chapter-17 blockquote` selector.

**Comment by djm858** [comment]
I hope that did it. I did something GitHub didn't like but it looks like I was able to do what you asked.

**Comment by acabal** [comment]
OK everything looks good, thanks!
